### ISSUE TITLE
Panic in handleRequests

### ISSUE THREAD

**Issue by chrisfduvall** [gliderlabs/ssh#102]
We recently upgraded to v0.1.3 from pre v0.1.1 (commit cff9b0c) so that we could utilize the `DefaultServerConfigCallback`. Once we released the update we started getting `panic`s when some customers tried to connect to our SSH server. We do not know what the customer was doing since it panicked before we were able to capture any customer information.

Any ideas on where we can start to debug this?

This is the error we have in our logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9144fe]
goroutine 10921 [running]:
github.com/wpengine/ssh-gateway/vendor/github.com/gliderlabs/ssh.(*Server).handleRequests(0xc0000d6540, 0x13a4340, 0xc0003ab1a0, 0xc000315680)
/go/src/github.com/wpengine/ssh-gateway/vendor/github.com/gliderlabs/ssh/server.go:275 +0xae
created by github.com/wpengine/ssh-gateway/vendor/github.com/gliderlabs/ssh.(*Server).handleConn
/go/src/github.com/wpengine/ssh-gateway/vendor/github.com/gliderlabs/ssh/server.go:255 +0x298
```

**Comment by belak** [comment]
It looks like there may have been an issue in some recently added code. I believe I've fixed the panic. I've tagged the latest commit as v0.1.4.
