### ISSUE TITLE
Get the actual port server is listening on

### ISSUE THREAD

**Issue by atulkc** [gliderlabs/ssh#114]
I am using this library to start ssh server during our tests. In order to have repeatable tests that can work anywhere, I want the ssh server to start on random port (available port). In order to do that I order to achieve that I did following:

```
server := &ssh.Server{
		Addr:       "127.0.0.1:0",
	}
```
Note that I used `0` as port to let OS choose the available port for me. And it works when I start the server using `server.ListenAndServe()`. However, I did not find a way to get the actual port number the listener is listening on. This makes it difficult for the test code to connect to the server that has been started. Essentially I am looking at having something similar to `httptest.Server.URL` that returns the actual address (ipaddr:port) the server is listening on. Is there a way to get this using existing functionality?

**Comment by belak** [comment]
Thanks for filing this!

Your best option would be to set up the listener directly and just use `.Serve(listener)` rather than `.ListenAndServe()`. Let me know if you have any issues with this.

**Comment by atulkc** [comment]
Sorry for really late reply. Github didn't notify me that there was a comment and I was using the workaround where I chose some high number for port that was most unlikely to be used on system. However, there is a possibility that on some systems there might be conflicts. I think what you propose is better as `Listener` will provide me with `Addr` method that will let me get the actual port number.

Thanks!
