### ISSUE TITLE
KeyboardInteractive ssh.Context lost the user information

### ISSUE THREAD

**Issue by xf0rk** [gliderlabs/ssh#116]
when testing with the xshell or the ssh client with the keyboardinteractive mode，I can't get the username but nil.

https://github.com/gliderlabs/ssh/blob/5b6cc7030f17095c0cf23bb063b0bfe824fe5f8b/server.go#L132

maybe there should be the applyConnMetadata(ctx, conn)  in the first line of the callback function.

**Comment by belak** [comment]
Thanks for doing the investigation here! I ended up adding this to master with credit to you for the actual commit.
