### ISSUE TITLE
Please how do I connect github with ssh from local host server

### ISSUE THREAD

**Issue by Kenomale** [gliderlabs/ssh#142]
I'm working on a micro job marketplace like task rabbit, fiverr etc. I'd like to download a source code that I found on github so I can deploy it on a local host server.

**Comment by belak** [comment]
Hello! Can you provide any more information about what you're trying to do? I have a feeling that you may need to find a higher level library or build one yourself, but maybe we can point you in the right direction.

**Comment by belak** [comment]
No additional information has been provided, so I'm closing this for now. Feel free to respond with more information and we'll try and help out.
