### ISSUE TITLE
debug1: send_pubkey_test: no mutual signature algorithm

### ISSUE THREAD

**Issue by SURA907** [gliderlabs/ssh#145]
OS: fedora 33
```
$ ssh -V
OpenSSH_8.4p1, OpenSSL 1.1.1i FIPS  8 Dec 2020
```
Carete ssh key with `ssh-keygen -t rsa -C "sura907@hotmail.com"

Then create a simple ssh server
```
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/gliderlabs/ssh"
)

func main() {
	addr := "0.0.0.0:2222"

	serve := &ssh.Server{
		Addr:             addr,
		Handler:          SessionHandler,
		PublicKeyHandler: PublicKeyHandler,
	}

	err := serve.ListenAndServe()
	if err != ssh.ErrServerClosed {
		fmt.Fprintf(os.Stdout, "ssh server %s now: %v", serve.Addr, err)
	}
	fmt.Println("close ssh server")
}

func PublicKeyHandler(ctx ssh.Context, key ssh.PublicKey) bool {
	return true
}

func SessionHandler(s ssh.Session) {
	io.WriteString(s, "hello, world!\n")
}
```

Some Command
```
$ ssh -T sura@localhost -p 2222
sura@localhost: Permission denied (publickey).
```

Then run ` ssh -v -T sura@localhost -p 2222`

It return `debug1: send_pubkey_test: no mutual signature algorithm`

When i remove the `PublicKeyHandler` from code, it works
```
$ ssh -T sura@localhost -p 2222
hello, world!
```

I found a document about this. But I don’t know if this problem belongs to the client or the server
> https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html

Should I not use rsa ssh key or is there any other solution?
Thtank u!

**Comment by olivierlemasle** [comment]
Cf https://github.com/golang/go/issues/37278

**Comment by SURA907** [comment]
Okay, I understand, I will close this issue
