### ISSUE TITLE
A fully ssh server example that micmic the openssh daemon

### ISSUE THREAD

**Issue by thetruechar** [gliderlabs/ssh#156]
We need a more elaborate server example that is fully functional like openssh daemon, thanks.

**Comment by gustavosbarreto** [comment]
This feature request does not align with the main goal of the project

**Comment by mohammed90** [comment]
> We need a more elaborate server example that is fully functional like openssh daemon, thanks.

@thetruechar, you're looking for github.com/mohammed90/caddy-ssh, but it's still under active development.
