### ISSUE TITLE
Reverse Port Forwarding get source

### ISSUE THREAD

**Issue by haylinmoore** [gliderlabs/ssh#157]
Currently ReversePortForwardingCallback seems to only provide the destination host and port. Is there a way to get the source? Like for somebody does -R 2223:1.1.1.1:22, I want to see they are trying to setup a reverse port forward to 1.1.1.1:22.

**Comment by MexHigh** [comment]
Why did you close this? Have you found a solution?

**Comment by smlx** [comment]
The last two components of `-R 2223:1.1.1.1:22` are happening on the local side, not the remote side. Therefore there is nothing to log, because the server doesn't have any information about what the local SSH client is doing with the connection.

**Comment by MexHigh** [comment]
@smlx Hmm ok I already thought so, thanks
