### ISSUE TITLE
Question - how to leave the connection open without a tty

### ISSUE THREAD

**Issue by chazsconi** [gliderlabs/ssh#171]
I'm trying to create a installable binary that supports the `-T` option (no tty) so I can use it to connect to with VSCode's remote option.

VSCode fails to connect with a `Failed to parse remote port from server output` error - I'm not certain, but I expect this is because it sends the `-T` option, but then the ssh server immediately closes the connection because there is no command or tty.

What code do I need to leave the connection open without having a tty?

**Comment by chazsconi** [comment]
Hi @ZhangKingsasa. In the end we used https://github.com/openssh/openssh-portable instead for our use case.

**Comment by gustavosbarreto** [comment]
> Hi @ZhangKingsasa. In the end we used https://github.com/openssh/openssh-portable instead for our use case.

@ZhangKingsasa Could you please close this issue?
