### ISSUE TITLE
About SSH

### ISSUE THREAD

**Issue by lastcall69** [gliderlabs/ssh#172]
Too many people not understand what function of SSH

**Comment by lastcall69** [comment]
I will accept who acknowledge about SSH

**Comment by bradfitz** [comment]
I don't understand. What is the purpose of this bug?

**Comment by belak** [comment]
Hi! Unfortunately this issue doesn't have enough information to figure out what you're looking for and no additional information was provided when requested.

If there's something you'd like us to look into, please comment with more information so we can reopen this issue.
