### ISSUE TITLE
golang/x/term Terminals do not work when SSH command is provided

### ISSUE THREAD

**Issue by MexHigh** [gliderlabs/ssh#235]
I'm trying to build a little terminal application with golang.org/x/term. Until now I only had one terminal which was started when I ran `ssh user@localhost`. But if SSH is given a command while starting the connection, the terminals no longer work (`terminal.ReadLine()` and `.ReadPassword("...")` never return and don't react to newlines).

This is a minimal example to reproduce this:

```go
package main

import (
	"io"

	"github.com/gliderlabs/ssh"
	"golang.org/x/term"
)

func main() {
	handler := func(s ssh.Session) {
		term := term.NewTerminal(s, "Enter your name: ")
		line, err := term.ReadLine()
		if err != nil {
			panic(err)
		}
		io.WriteString(s, "Your name is: "+line+"\n")
	}

	server := ssh.Server{
		Addr:    ":2222",
		Handler: handler,
	}
	server.SetOption(ssh.HostKeyFile("./id_ed25519"))
	panic(server.ListenAndServe())
}
```

When I run `ssh user@localhost -p 2222`, it works:

![image](https://github.com/user-attachments/assets/c44ff80d-aa92-4ba1-87a7-ba8b5814cc40)

But when a append any command to SSH nothing happens at `ReadLine()`, no matter how often I press Enter: However, my input is somehow "reflected" into the SSH window, which is not the case without the command (maybe this is the reason, why `ReadLine()` never returns?):

![image](https://github.com/user-attachments/assets/7ba971fe-3c80-4360-8300-6662f7e8826f)

---

This is my `go.mod` if required:

```go
module my-turn

go 1.20

require (
	github.com/gliderlabs/ssh v0.3.7
	golang.org/x/term v0.23.0
)

require (
	github.com/anmitsu/go-shlex v0.0.0-20200514113438-38f4b401e2be // indirect
	golang.org/x/crypto v0.26.0 // indirect
	golang.org/x/sys v0.24.0 // indirect
)
```

I tried debugging this for some time now, but I don't get why this is not working. Any ideas how to fix this? Or is this a bug?

**Comment by MexHigh** [comment]
Just found out that it works with `ssh user@localhost -tt -p 2222 some-command`. Is there any way to accomplish this in the backend implementation? Or is this a limitation of the SSH client?

**Comment by smlx** [comment]
As per the [ssh](https://man7.org/linux/man-pages/man1/ssh.1.html#AUTHENTICATION) man page, a [pty](https://man7.org/linux/man-pages/man7/pty.7.html) will only be requested for an interactive session by default. When a command is supplied, it is executed in a non-interactive session.

A pty has a client and a server side, so both your client needs to request the pty and the server needs to accept the request (this library does by default). So no, there is no way for a server to force a client to use a pty.

[This video](https://www.youtube.com/watch?v=2XLZ4Z8LpEE) might help visualise exactly what is being emulated by the pty.

**Comment by MexHigh** [comment]
Ok that makes sense. Thanks for the explaination!
