### ISSUE TITLE
Read user input

### ISSUE THREAD

**Issue by monopollly** [gliderlabs/ssh#32]
Hi!

I want to make a little shell for my app,
could you help me to understand how I can to wait user input commands?

I this something like that
but its not working(

```go
ssh.Handle(func(s ssh.Session) {
      reader := bufio.NewReader(s)
      input, _ := reader.ReadString('\n')
      io.WriteString(s, "\n"+input)
})
```

thank you!

**Comment by hloeffler** [comment]
this is no issue

but use:

	import "golang.org/x/crypto/ssh/terminal"

	ssh.Handle(func(s ssh.Session) { ...

	term := terminal.NewTerminal(s, PROMT)

**Comment by monopollly** [comment]
cool thanks!

**Comment by hloeffler** [comment]
sure, glad it helped

@progrium close? and maybe add links to examples to README.md ?
