### ISSUE TITLE
Request for example

### ISSUE THREAD

**Issue by literadix** [gliderlabs/ssh#35]
This is a great peace of software. Thank you very much. Could you please post an example how to write a client as go routine which is waiting for user input lines and which answers each lines after processing it? Thank you very much.

```go
ssh.Handle(func(s ssh.Session) {
		log.Printf("%s", s.RemoteAddr())
		io.WriteString(s, fmt.Sprintf("Hello %s\n", s.User()))

                // ... handle connection until it closes by user input, client close
                // ??????
	})
```

Thank you very much in advance.

**Comment by progrium** [comment]
I don't understand, do you want a client example or a server example? This is a server library.

**Comment by mattaitchison** [comment]
@literadix Is this what you wanted?

	ssh.Handle(func(s ssh.Session) {
		scanner := bufio.NewScanner(s)
		for scanner.Scan() {
			fmt.Fprintln(s, "got:", scanner.Text())
		}
	})

**Comment by literadix** [comment]
Yes,

this is great. Thank you very much for your quick help. I will implement a
ssh honey pot. I have many ssh log in failures and I do want to see what
they are looking for :-)

BR

Maciej

2017-04-19 3:16 GMT+02:00 Matt Aitchison <notifications@github.com>:

**Comment by belak** [comment]
I tried editing your code to put it inside a code block, but I guess comments which have been emailed in don't support that... it's weird.

Anyway, there are a few issues with your code. It's a bit easier to handle input properly if you don't use a Pty, so adding ssh.NoPty() to the Options portion of ListenAndServe will make it easier to work with, but you won't be able to use some of the advanced features.

Your current code also passes ssh.PasswordAuth to log.Fatal, but it should be passed to ssh.ListenAndServe... which is why that isn't working.

**Comment by literadix** [comment]
Hello,

I tried is with ssh.NoPty. This is also not working. I am using the standard ssh linux ssh client without any options. The code is now like this:

package main

import (
	"bufio"
	"fmt"
	"io"
	"log"

	"github.com/gliderlabs/ssh"
)

func main() {
	ssh.Handle(func(s ssh.Session) {

		io.WriteString(s, "Hello world\n")
		scanner := bufio.NewScanner(s)
		fmt.Println("1")

		for scanner.Scan() {
			fmt.Println("2")
			fmt.Fprintln(s, "got:", scanner.Text())
		}

	})

	log.Fatal(ssh.ListenAndServe(":2222", nil), ssh.NoPty())
}

In my client I see "Hello world", on my program console I see just "1". It hangs redings lines from the client. "2" is not displayed.

**Comment by belak** [comment]
Look at the last line. You have

```
log.Fatal(ssh.ListenAndServe(":2222", nil), ssh.NoPty())
```

but it should be

```
log.Fatal(ssh.ListenAndServe(":2222", nil, ssh.NoPty()))
```

I also mentioned that in my previous comment.

**Comment by literadix** [comment]
This is great, it is working. I get the following output:


Warning: Permanently added '[ws-mab]:2222,[10.128.52.93]:2222' (RSA) to the
list of known hosts.
PTY allocation request failed on channel 0
Hello world
asdasd
got: asdasd
asdasd
got: asdasd
adasd
got: adasd
asdasd
got: asdasd


Could you please provide an example with PTY?

Thank you very much in advance !

Maciej


2017-04-19 9:57 GMT+02:00 Kaleb Elwert <notifications@github.com>:

**Comment by literadix** [comment]
Hello,

has any body a suggestion how to avoid "PTY allocation request failed on channel 0" ? Do I have to provide a PTY layer in my SSH server. Could anyone provide an example how this could be done? I do want not to use a bash, but parse the input lines directly. Is start my ssh client as this:

ssh -p 2222 hostname

Thank you very much.

Maciej

**Comment by progrium** [comment]
If you're going to be building an SSH server, I suggest you read up on the SSH protocol and also the man pages for the OpenSSH client.

**Comment by hloeffler** [comment]
or maybe just google: "golang ssh honeypot":
https://github.com/ashmckenzie/sshoney

**Comment by progrium** [comment]
I'll try to be a bit more helpful than my last reply before I close this issue. The OpenSSH client is going to try to allocate a PTY when you connect without a specific command. However, your server code is using the NoPty configuration, so it denies the request. If you remove that, it won't deny it and you then have the option of working with Pty using the information from the Pty() method on Session, which is entirely optional and as far as I understand unnecessary for your use case.
