### ISSUE TITLE
Channels?

### ISSUE THREAD

**Issue by shurco** [gliderlabs/ssh#40]
Hello!
How do I send a message through a channel?
(Open session and send messages via channel)
Thx

**Comment by progrium** [comment]
The same channel as the session? A different channel? Is this something custom or are you trying to implement some protocol?

**Comment by shurco** [comment]
Hello,
my example code:

```
ssh.Handle(func(s ssh.Session) {
			testUser := "root"
			testPass := "password"
			testServer:= "192.168.1.240:2022"

			config := &gossh.ClientConfig{
				User: testUser,
				Auth: []gossh.AuthMethod{
					gossh.Password(testPass),
				},
			}

			client, err := gossh.Dial("tcp", testServer, config)
			if err != nil {
				log.Fatal(err)
			}
			session, err := client.NewSession()
			if err != nil {
				log.Fatal(err)
			}
			defer session.Close()

			/* ?? how sent to channel and show connect into display  ?? */

})
```

**Comment by progrium** [comment]
I'm still very confused. So you're trying to make a gateway or a proxy? In your example you say established SSH server... there are two. The one you made and the one you connected to. What do you mean by channel?

**Comment by shurco** [comment]
Ok, I'm trying to make a gateway.

**Comment by progrium** [comment]
There are some examples you can reference for parts of it. Otherwise ... I mean it's pretty straightforward and you're not telling me what you don't know so that I can help. But I guess to point you in the right direction from where you're at, you'll want to use `io.Copy` twice to copy data from the inner session to the outer session. Google around for making proxies and that would give you an idea of what I mean.

**Comment by shurco** [comment]
Everything is very simple
I want to implement tunneling between servers
For example, I connect to the ssh server with a welcome key, and the server connects to another server via a password.
I <-> ssh server on local network <-> remote ssh server

P.S. Sorry for my english)

**Comment by progrium** [comment]
Yep, I got the gateway idea now. I think what's missing from your example code is not specific to SSH (other than PTY, which you might just need to read up on, re-read the godocs, and look at some of the examples in this repo). I also recommend you read up on using `io.Copy`.

So if you have *specific* questions about some aspect of using this library, you can open a new issue. Good luck!

**Comment by shurco** [comment]
Ok, I updated my example and add PTY, but I can not get a response from the remote server to the console: 



`
ssh.Handle(func(s ssh.Session) {

         sshconfig := &gossh.ClientConfig{
            User: root,
            Auth: []gossh.AuthMethod{
                gossh.Password(password),
            },
            HostKeyCallback: gossh.InsecureIgnoreHostKey(),
        }

       ptyReq, _, isPty := s.Pty()

        if isPty {
            remoteConnect, err := gossh.Dial("tcp", 192.168.1.240:2022, sshconfig)
            if err != nil {
                log.Printf("dial error: %s", err.Error())
                return
            }
            log.Printf("%s -> %s connected.", s.RemoteAddr(), remoteConnect.RemoteAddr())
            defer remoteConnect.Close()

            session, err := remoteConnect.NewSession()
            if err != nil {
                log.Printf("Failed to create session %s", err.Error())
                return
            }
            defer session.Close()

            //session.Stdin = os.Stdin
            //session.Stdout = os.Stdout
            //session.Stderr = os.Stderr

            termModes := gossh.TerminalModes{
                gossh.ECHO:          0,
                gossh.TTY_OP_ISPEED: 14400,
                gossh.TTY_OP_OSPEED: 14400,
            }

            err = session.RequestPty(ptyReq.Term, ptyReq.Window.Height, ptyReq.Window.Width, termModes)
            if err == nil {
                err = session.Shell()
            }
            if err != nil {
                log.Printf("Failed to send shell command: %s", err.Error())
            }

            io.WriteString(s, "Hello world\n") // отправить текст в терминал пользователя

            /* ?? How can I get the service console of established ssh server via channel? Tty doesn't work for me  ?? */

            log.Printf("%s -> %s closed", s.RemoteAddr(), remoteConnect.RemoteAddr())
        } else {
            io.WriteString(s, "No PTY requested.\n")
            s.Exit(1)
        }
    })
`


Please help me solve this problem.
