### ISSUE TITLE
Cancel the Session.Conetxt() when client connection closes

### ISSUE THREAD

**Issue by tsl0922** [gliderlabs/ssh#45]
**Reference**: https://godoc.org/net/http#Request.Context

> For outgoing client requests, the context controls cancelation.
>
> For incoming server requests, the context is canceled when the client's connection closes, the > request is canceled (with HTTP/2), or when the ServeHTTP method returns.

This is useful for using `Session.Conetxt()` to do something in background.

**Comment by progrium** [comment]
Yep, would be great!

**Comment by progrium** [comment]
I was about to add a CloseNotifier type API, but this is even better.
