### ISSUE TITLE
Support remote port forwarding

### ISSUE THREAD

**Issue by klausenbusk** [gliderlabs/ssh#53]
Hello

Is there any plans to support remote port forwarding?
Researching a bit it seems to require support of the two channels type `tcpip-forward` and `forwarded-tcpip`, and I found a working "example" here: https://github.com/tunneled/tunneled-server/blob/master/tunneled-server.go

Regards Kristian Klausen

**Comment by progrium** [comment]
If there isn't an issue and it's not on the [roadmap](https://github.com/gliderlabs/ssh#roadmap) then the answer is no. However, that doesn't mean it won't happen, as long as somebody like yourself is willing to contribute it.

**Comment by progrium** [comment]
I started a branch for remote forwarding here:
https://github.com/gliderlabs/ssh/tree/remote-forwarding

I live streamed it on YouTube if anybody is interested:
https://www.youtube.com/watch?v=PdmW1awXb5E

**Comment by progrium** [comment]
@klausenbusk any chance I can get you to try that branch? There is a PR open for it now:
https://github.com/gliderlabs/ssh/pull/60

**Comment by bamoo456** [comment]
Hi 
Is there any plans to release this enhancement recently?

**Comment by progrium** [comment]
I will try to get that PR up to date and ready to merge!

**Comment by bamoo456** [comment]
Cool, thanks for the update

**Comment by eliastor** [comment]
Any news?

**Comment by progrium** [comment]
I think there were some issues on the PR. Maybe you can contribute some fixes.
