### ISSUE TITLE
HostKeyFile Not support ED25519

### ISSUE THREAD

**Issue by fcharlie** [gliderlabs/ssh#56]
When I use `ssh.HostKeyFile` add a `/etc/ssh/ssh_host_ed25519_key`, Start ssh server error, Report: `unsupported key type 'OPENSSH PRIVATE KEY'`

In fact, when i use `ssh.ParsePrivateKey`(x/crypto/ssh),  it can support **ed25519**
```go
func AddHostKeyFile(filepath string, srv *ssh.Server) {
	pemBytes, err := ioutil.ReadFile(filepath)
	if err != nil {
		log.Printf("AddHostKeyFile: %s", err)
		return
	}
	hostKey, err := gossh.ParsePrivateKey(pemBytes)
	if err != nil {
		log.Printf("Fatal to parse host key: %s, %s", filepath, err)
		return
	}
	srv.AddHostKey(hostKey)
	return
}
```

Bug in: 
https://github.com/gliderlabs/ssh/blob/4a4de396c4d49400d09e0b4d83053a01539e4bcc/util.go#L14

```go
func signerFromBlock(block *pem.Block) (ssh.Signer, error) {
	var key interface{}
	var err error
	switch block.Type {
	case "RSA PRIVATE KEY":
		key, err = x509.ParsePKCS1PrivateKey(block.Bytes)
	case "EC PRIVATE KEY":
		key, err = x509.ParseECPrivateKey(block.Bytes)
	case "DSA PRIVATE KEY":
		key, err = ssh.ParseDSAPrivateKey(block.Bytes)
	default:// NOT parse ed25519
		return nil, fmt.Errorf("unsupported key type %q", block.Type)
	}
	if err != nil {
		return nil, err
	}
	signer, err := ssh.NewSignerFromKey(key)
	if err != nil {
		return nil, err
	}
	return signer, nil
}
```

**Comment by progrium** [comment]
Yep, easy fix is to use `ssh.ParsePrivateKey` from `x/crypto/ssh`. I don't believe it existed at the time. Would love a PR.

**Comment by belak** [comment]
It looks like signerFromBlock is pretty close to a direct copy from [ParseRawPrivateKey](https://github.com/golang/crypto/blob/master/ssh/keys.go#L806). The main downside to ssh.ParsePrivateKey is that it only supports a single private key block, while the code here supports adding multiple keys from a single file.

**Comment by progrium** [comment]
I don't think it's very common for an SSH key to have more than key in a file, right? I'd love to optimize for less code to maintain here.

**Comment by belak** [comment]
Not that I'm aware of. It would be a trivial fix to rip out the custom code and move to gossh.ParsePrivateKey as long as we're aware it would break this specific case.

**Comment by progrium** [comment]
I'm down, now is the time to break stuff pre-1.0 still.

**Comment by progrium** [comment]
@fcharlie can you pull master and let us know if this is still an issue?

**Comment by fcharlie** [comment]
OK, it work !
