### ISSUE TITLE
Support subsystem, E.g sftp

### ISSUE THREAD

**Issue by nxsre** [gliderlabs/ssh#63]
rt

**Comment by progrium** [comment]
Is this specifically for sftp or for an interface for building multiple subsystems?

**Comment by viroos** [comment]
this is for support:
a) ssh user@server -s subsystem
b) support apps that relay on subsystems definitions (for example sftp)

**Comment by gustavosbarreto** [comment]
Please see https://github.com/gliderlabs/ssh/pull/103#issuecomment-660362656
