### ISSUE TITLE
Make it possible to only allow one channel per connection

### ISSUE THREAD

**Issue by belak** [gliderlabs/ssh#7]
I'm running a fairly large SSH service and we've been looking at moving to an ssh wrapper library (rather than working on our own) and this is one of the things we do to make it easier to scale (so we know there's only one operation happening on each host)

**Comment by belak** [comment]
In particular, at the session channel level. This loops through all session channel requests and allows all of them.

**Comment by progrium** [comment]
So maybe some kind of session policy callback?

**Comment by belak** [comment]
This is one of the ones I'm not too sure on the design of. When we implemented this we just hard-coded it but I know that's not what most people want.
