### ISSUE TITLE
Winsize problems

### ISSUE THREAD

**Issue by tombh** [gliderlabs/ssh#81]
Just on the off chance that someone might have some clues for me. Here's my SSH server implementation: https://github.com/browsh-org/baas/blob/master/ssh-server/ssh-server.go

On connection the TTY size is reported as 0x0, and then upon TTY resizes, only the width is updated. I don't have many ideas where to start debugging this. Any ideas whatsoever most appreciated.

**Comment by progrium** [comment]
Oh interesting. I don't remember if openssh shares this in debug, but try connecting with all the debug variables on to try and see what it's actually sending. I trust the upstream crypto/ssh is doing things right, so if you wanted to play around with our code you could look around these to places:

https://github.com/gliderlabs/ssh/blob/master/session.go#L273
https://github.com/gliderlabs/ssh/blob/master/session.go#L248

First is handling window change messages, you can print out the bytes we get from the wire there. Similarly the second is the initial window size that comes with the pty request message.

**Comment by tombh** [comment]
Ha, so I updated `gliderlabs/ssh` and `kr/pty` and the problem vanished. I'm glad it's fixed but I could have at least double checked that before posting here, sorry. Your links made me realise I don't actually have those lines!

Thanks so much.
