### ISSUE TITLE
Make it possible to log errors in the ssh protocol

### ISSUE THREAD

**Issue by belak** [gliderlabs/ssh#9]
As an example, handleConn in server.go just drops errors when they happen at the protocol level. This is particularly important when there are changes pushed out to x/crypto/ssh which break certain clients.

**Comment by progrium** [comment]
Right :)

Do you have examples of libraries that handle logging well? I'm not a fan of libraries that come with their own logging or using `log` without your permission...

**Comment by belak** [comment]
For the library we built, we added a callback. Something like `ErrorHandler func(ctx *context.Context, msg string, err error)`.

This lets anyone building on top of this library implement their own logging.

**Comment by progrium** [comment]
Yep. I prefer callbacks for handling logging but wasn't sure if people were down with that model.

**Comment by hloeffler** [comment]
i prefer callbacks over logging

**Comment by progrium** [comment]
I guess we can close this in favor of #10 ?

**Comment by belak** [comment]
Sounds good to me.
