### ISSUE TITLE
Tag version with reverse port forwarding support?

### ISSUE THREAD

**Issue by binwiederhier** [gliderlabs/ssh#94]
Hey there. Great library. Thanks very much!

The current master version includes reverse port forwarding support, but there is no tagged version that supports it. I'm tying to used tagged versions only with Go modules, instead of just pointing to master. 

Could you tag the current master to make that possible?

**Comment by progrium** [comment]
Here you go! https://github.com/gliderlabs/ssh/releases/tag/v0.1.2

**Comment by binwiederhier** [comment]
Awesome thanks!
