### ISSUE TITLE
Allow to request PTY even if rows/cols are zero

### ISSUE THREAD

**Issue by rschmied** [gliderlabs/ssh#97]
For automation tasks, the SSH client can request a PTY with `-t` or `-tt` even if there's no TTY because stdin/stdout is redirected as part of a script or tool... like here:

```plain
ssh -tt somehost  << EOF
stty -a
exit
EOF
```

which results in 

```plain
$ stty -a
speed 38400 baud; rows 0; columns 0; line = 0;
...
```

However, code in utils actually requires the cols and rows to be >0 and thus will deny a PTY. OpenSSH (where the example above is from) works just fine in this case.

I'm suggesting to remove the logic to enforce rows and columns to be >0... A PTY of size 1x1 is pretty much as unusable as one with 0x0 :)

In a fork I did, I removed the logic and it works just fine for me... Wondering what the general consensus here is?

**Comment by belak** [comment]
I *think* that the general idea was to deny invalid requests. Because these values will be 0 when not set in the request, we opted for denying them. However, you have a good reason for wanting this, so I'll try to get this changed soon.

**Comment by belak** [comment]
Fixed in ef6d890

**Comment by shazow** [comment]
I think this issue is completed, please re-open if I'm mistaken. :)

**Comment by belak** [comment]
Yep, thanks for following up

**Comment by 871690991** [comment]
I also met, how to solve this problem
