### ISSUE TITLE
bug: connection killed whenever MaxTimeout is not set but IdleTimeout is

### ISSUE THREAD

**Issue by czoczo** [gliderlabs/ssh#99]
This is similar to #51 but other way around.
### Way to reproduce:
```
set value for IdleTimeout, e.g. 10 sec
omit value for MaxTimeout
```
### What is expected:
When connection is idle for 10 sec, it should be killed
### What actually happens:
Connection gets killed after 10 sec no matter how active the connection is

**Comment by belak** [comment]
Fixed in 9253a53eda6d496306693fc247b7819a204040c1
